learning_users/basic_app/urls.py
from basic_app import views
from django.conf.urls import url

# Template urls
app_name = 'basic_app'
urlpatterns = [
    url(r'^register/$',views.register,name='register'),
]

learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^admin/', admin.site.urls),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User    ####   Importing User model
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)  # Creating one to one relationship with model User so that we can add more Field
    # User is inbuilt model in Django
    #additional Field inserting here
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):    #  printing the default string
        return self.user.username     #  username is the default of User model

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from myapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm
# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)  # grabbing the user form data in user_form variable
        profile_form = UserProfileInfoForm(data=request.POST)  # Grabbing the profile form in profile_form
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()    # saving the user form to the databse
            user.set_password(user.password)  # Hashing the password
            user.save()   # save the hash password to the database
            profile = profile_form.save(commit=False) # We are not saving the profile form to the databse yet. This is bcoz with the conflicting with user form
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm() # if the request is not a POST request then we just create an instance of class UserForm() instead of invalidating and saving it to further
        profile_form = UserProfileInfoForm()  #Similer instance of class UserProfileInfoForm
    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,
                'registered':registered}) # passing context dictnory variable referenced in registration.html file

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top navbar-inverse'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="#" class="navbar-brand" href="{% url 'index' %}">ATP Cloud</a></li>
          <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
          <li><a href="{% url 'basic_app:register' %}" class="navbar-link">Register</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to cloud computing</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}
  {% if registered %}  <!-- Template tagging for boolean registered -->
    <h2>Thank you for registering!</h2>
    {% else %}
      <h2>Register Here!</h2>
      <h2>Fill Out the form now!</h2>
      <form enctype="multipart/form-data" method="post"> <!-- "multipart/form-data" for multimedia files -->
          {% csrf_token %}   <!-- Enabling csrf token for registration form -->
        {{ user_form.as_p }}  <!-- Template tagging for user form  -->
        {{ profile_form.as_p }}  <!-- Template tagging for profile form -->
        <input type="submit" class="btn btn-primary" value="Register">
      </form>
  {% endif %}
{% endblock %}