django_folder/hadoop_start/hadoop_start/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^formpage/',views.form_name_view,name='form_page'),
    url(r'^myapp',include('myapp.urls')),
]

django_folder/hadoop_start/myapp/urls.py
from myapp import views
from django.conf.urls import url

# Template urls
app_name = 'myapp'
urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^staas/$',views.form_name_view,name='staas'),
    url(r'^saas/$',views.SaasService,name='saas'),
    url(r'^iaas/$',views.IaasService,name='iaas'),
]

django_folder/hadoop_start/myapp/models.py
from django.db import models
from django.contrib.auth.models import User    ####   Importing User model
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)  # Creating one to one relationship with model User so that we can add more Field
    # User is inbuilt model in Django
    #additional Field inserting here
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):    #  printing the default string
        return self.user.username     #  username is the default of User model

# class UserFormName(models.Model):
#     user = models.OneToOneField(User)
#     uname = models.CharField(blank=True)
#     dir_name = models.CharField(blank=True)
#     size = models.IntegerField(blank=True)

django_folder/hadoop_start/myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from myapp.models import UserProfileInfo

class StorageFormName(forms.Form):
        name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
        storage_dir = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
        #storage_type = forms.CharField()
        CHOICES=[('choice1','Object Storage'),
         ('choice2','Block Storage')]
        storage_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
        storage_security_choices = (('select1', 'Secure'),('select2', 'Not Secure'),('select3', 'High Available(HA)'),)
        storage_security = forms.CharField(widget=forms.Select(choices = storage_security_choices,attrs={'class' : 'form-control'}))
        size = forms.IntegerField(widget=forms.NumberInput(attrs={'class' : 'form-control'}))

class IaasForm(forms.Form):
    vm_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}),label='VM Name')
    CHOICES=[('select1','Windows'),('select2','Linux')]
    client_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(),label='Are you a ?')
    instance_choices1 = (('select1', 'Linux'),('select2', 'Windows'),)
    instance_type = forms.CharField(widget=forms.Select(choices = instance_choices1,attrs={'class' : 'form-control'}),label='Instance Type')
    instance_choices2 = (('select1', 'Ubuntu'),('select2', 'Kali'),('select3', 'linuxmint'),('select4', 'RHEL6'),('select5', 'RHEL7'),)
    instance_variant = forms.CharField(required=False, widget=forms.Select(choices = instance_choices2,attrs={'class' : 'form-control'}),label='Instance Variant')
    RAM = forms.IntegerField(widget=forms.NumberInput(attrs={'class' : 'form-control'}),label='RAM')
    vCPUs = forms.IntegerField(widget=forms.NumberInput(attrs={'class' : 'form-control'}),label='Virtual CPUs')
    HDD = forms.IntegerField(widget=forms.NumberInput(attrs={'class' : 'form-control'}),label='Hard Disk')
    network_inst_choices = (('select1', 'Via img file'),('select2', 'Via FTP'),('select3', 'Via HTTP'))
    network_install_type = forms.CharField(widget=forms.Select(choices = network_inst_choices,attrs={'class' : 'form-control'}),label='Network Installation Type')
    CHOICES=[('select1','Yes'),
     ('select2','No')]
    bridge = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(),label='Do you want Bridge Connectivity ?')
    provision_choices = (('select1','Enable Thick Provisioning'),('select2','Enable Thin Provisioning'))
    provision = forms.CharField(widget=forms.Select(choices = provision_choices,attrs={'class' : 'form-control'}),label='Which Provisioning do you want ?')
    access_choices = (('select1', 'Through TigerVNC'),('select2', 'Through NoVNC'),)
    access_type = forms.CharField(widget=forms.Select(choices = access_choices,attrs={'class' : 'form-control'}),label='Access Type')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')

class SaasForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    software_choices = (('select1', 'firefox'),('select2', 'atom editor'),('select3', 'terminal'),('select4' , 'xterminal'),('select5' , 'Google Chrome'),('select6', 'virt-manager'),('select7', 'virt-viewer'))
    software_name = forms.CharField(widget=forms.Select(choices = software_choices,attrs={'class' : 'form-control'}))
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

django_folder/hadoop_start/myapp/views.py
from django.shortcuts import render,redirect
from myapp import forms
from myapp.forms import UserForm,UserProfileInfoForm,SaasForm,IaasForm
from os import system
import urllib
from django.http import HttpResponse,HttpResponseRedirect
# Create your views here.

myip = '192.168.43.188'


def index(request):
    return render(request,'myapp/index.html')

def IaasService(request):
    form = forms.IaasForm()
    if request.method == 'POST':
        form = forms.IaasForm(request.POST)
        if form.is_valid():
            client_type = form.cleaned_data['client_type']
            vm_name = form.cleaned_data['vm_name']
            instance_type = form.cleaned_data['instance_type']
            instance_variant = form.cleaned_data['instance_variant']
            ram = form.cleaned_data['RAM']
            vcpu = form.cleaned_data['vCPUs']
            size = form.cleaned_data['HDD']
            network_install_type = form.cleaned_data['network_install_type']
            bridge_connectivity = form.cleaned_data['bridge']
            provision = form.cleaned_data['provision']
            access_type = form.cleaned_data['access_type']
            def myFun(img_type):
                if network_install_type == 'select1':
                    print('You Selected installation via IMG')
                    if provision == 'select1':
                        print('Thick Provisioning')
                        if access_type == 'select1':
                            print('TigerVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type linux --cdrom  /images_files/{} --disk=/iaas/{}.img,size={} --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5911  --noautoconsole".format(vm_name,ram,vcpu,img_type,vm_name,size))
                            #print(instance_variant)
                            #print(instance_type)
                        else:
                            print('NOVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type  linux --cdrom /images_files/{} --disk=/iaas/{}.img,size={} --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5913  --noautoconsole".format(vm_name,ram,vcpu,img_type,vm_name,size))
                    else:
                        print('Thin Provisioning')
                        system("qemu-img create -f qcow2  /iaas/{}.qcow2  {}".format(vm_name,size))
                        if access_type == 'select1':
                            print('TigerVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type linux --cdrom /images_files/{} --disk=/iaas/{}.qcow2  --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5910  --noautoconsole".format(vm_name,ram,vcpu,img_type,vm_name))
                        else:
                            print('NOVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type linux --cdrom /images_files/{} --disk=/iaas/{}.qcow2  --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5914  --noautoconsole".format(vm_name,ram,vcpu,img_type,vm_name))
                elif network_install_type == 'select2':
                    print('You Selected installation FTP')
                    if provision == 'select1':
                        print('Thick Provisioning')
                        if access_type == 'select1':
                            print('TigerVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type linux  --location ftp://{}/pub/{}  --disk=/iaas/{}.img,size={} --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5915  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name,size))

                        else:
                            print('NOVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type linux  --location ftp://{}/pub/{}  --disk=/iaas/{}.img,size={} --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5916  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name,size))

                    else:
                        print('Thin Provisioning')
                        system("qemu-img create -f qcow2  /iaas/{}.qcow2  {}".format(vm_name,size))
                        if access_type == 'select1':
                            print('TigerVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type  linux --location ftp://{}/pub/{}  --disk=/iaas/{}.qcow2  --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5917  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name))

                        else:
                            print('NOVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type linux  --location ftp://{}/pub/{}  --disk=/iaas/{}.qcow2  --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5918  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name))

                else:
                    print('You Selected installation HTTP')
                    if provision == 'select1':
                        print('Thick Provisioning')
                        if access_type == 'select1':
                            print('TigerVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type  linux  --location http://{}/{}  --disk=/iaas/{}.img,size={} --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5919  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name,size))

                        else:
                            print('NOVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type  linux   --location http://{}/{}  --disk=/iaas/{}.img,size={} --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5920  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name,size))

                    else:
                        print('Thin Provisioning')
                        system("qemu-img create -f qcow2  /iaas/{}.qcow2  {}".format(vm_name,size))
                        if access_type == 'select1':
                            print('TigerVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type  --location http://{}/{}  --disk=/iaas/{}.qcow2  --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5921  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name))

                        else:
                            print('NOVNC')
                            system("virt-install --name {} --memory {} --vcpus {} --os-type   --location http://{}/{}  --dis/iaas/{}.qcow2  --network  bridge=mybr --graphics vnc,password=redhat,listen=0.0.0.0,port=5922  --noautoconsole".format(vm_name,ram,vcpu,myip,instance_variant,img_type,vm_name))

            if client_type == 'select1':
                print("You are window client")
            else:
                print('you are linux client')
                if instance_type == 'select1':
                    print('instance type is Linux')
                    if instance_variant == 'select1':
                        print('You required Ubuntu')
                        img_type = 'ubuntu-14.04-desktop-amd64.iso'
                        myFun(img_type)
                    elif instance_variant == 'select2':
                        print('You required kali linux')
                        img_type = 'kali-linux-2016.2-amd64.iso'
                        myFun(img_type)
                    elif instance_variant == 'select3':
                        print('You required LinuxMint')
                        img_type = 'linuxmint-11-gnome-dvd-64bit.iso'
                        myFun(img_type)
                    elif instance_variant == 'select4':
                        print('You required RHEL6')
                        img_type = 'rhel-server-6.4-x86_64-dvd.iso'
                        myFun(img_type)
                    else:
                        print('You required RHEL7')
                        img_type = 'rhel-server-7.2-x86_64-dvd.iso'
                        myFun(img_type)
                else:
                    print('instance type is Windows')


    return render(request,'myapp/iaas.html',{'form' : form})

def SaasService(request):
    form = forms.SaasForm()
    if request.method == 'POST':
        form = forms.SaasForm(request.POST)
        if form.is_valid():
            #Do something code here
            cip = request.META.get('REMOTE_ADDR')
            cname = form.cleaned_data['name']
            sft_name = form.cleaned_data['software_name']
            list_of_software = {'select1' : 'firefox','select2' : 'atom','select3' : 'gnome-terminal','select4' : 'xterm','select5' : 'google-chrome','select6' : 'virt-manager','select7' : 'virt-viewer'}
            def mySoftware():
                system('useradd -s  /usr/bin/{}  {}'.format(list_of_software[sft_name],cname))
                system("echo '{}' |  passwd  {}  --stdin".format(cname,cname))
                #system("setfacl -m  u:{}:rx  /usr/bin/{}".format(cname,list_of_software[sft_name]))   (Removing acc. based restriction)
                fh = open('/root/Desktop/{}.sh'.format(cname),'a+')
                fh.write("#! /bin/bash\n\nsshpass -p '{}' ssh -o StrictHostKeyChecking=no -X -l {} {} {}".format(cname,cname,myip,list_of_software[sft_name]))
                fh.close()
                system('chmod +x /root/Desktop/{}.sh'.format(cname))
                status = system("sshpass -p 'redhat' scp -o StrictHostKeyChecking=no /root/Desktop/{}.sh  root@{}:/root/Desktop/".format(cname,cip))

django_folder/hadoop_start/templates/myapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top navbar-inverse'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="#" class="navbar-brand" href="{% url 'index' %}">ATP Cloud</a></li>
          <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
          <!-- <li><a href="{% url 'myapp:register' %}">SAAS</a></li> -->
          <li><a href="{% url 'myapp:staas' %}">STAAS</a></li>
          <li><a href="{% url 'myapp:saas' %}">SAAS</a></li>
          <li><a href="{% url 'myapp:iaas' %}">IAAS</a></li>
          <!-- <li><a href="{% url 'myapp:register' %}">IAAS</a></li> -->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'myapp:register' %}" class="navbar-link">Register</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

django_folder/hadoop_start/templates/myapp/iaas.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}
{% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <form action="" method="post">
        <h3>Fill out the form to get infrastructure!</h3>
        <div class="form-group">
          {{ form.as_p }}
          {% csrf_token %}
        </div>
          <center><input type="submit" class="btn btn-primary btn-lg" value="submit"/></center>
        </form>
      </div>
{% endblock %}

django_folder/hadoop_start/templates/myapp/index.html
{% extends "myapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h3>Welcome to cloud computing</h3>
  <h3>Services:</h3>
  <ul>
    <h3><li>Software as a service (SAAS)</li></h3>
    <h3><li>Storageas a service (STAAS)</li></h3>
    <h3><li>Infrastructure as a service (IAAS)</li></h3>
  </ul>
</div>

{% endblock %}

django_folder/hadoop_start/templates/myapp/registration.html
{% extends 'myapp/base.html' %}
{% load staticfiles %}

{% block body_block %}
  {% if registered %}  <!-- Template tagging for boolean registered -->
    <h2>Thank you for registering!</h2>
    {% else %}
      <h2>Register Here!</h2>
      <h2>Fill Out the form now!</h2>
      <form enctype="multipart/form-data" method="post"> <!-- "multipart/form-data" for multimedia files -->
          {% csrf_token %}   <!-- Enabling csrf token for registration form -->
        {{ user_form.as_p }}  <!-- Template tagging for user form  -->
        {{ profile_form.as_p }}  <!-- Template tagging for profile form -->
        <input type="submit" class="btn btn-primary" value="Register">
      </form>
  {% endif %}
{% endblock %}

django_folder/hadoop_start/templates/myapp/saas.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}
{% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <form action="" method="post">
        <h3>Fill out the form!</h3>
        <div class="form-group">
          {{ form.as_p }}
          {% csrf_token %}
        </div>
          <center><input type="submit" class="btn btn-primary" value="submit"/></center>
        </form>
      </div>
{% endblock %}

django_folder/hadoop_start/templates/myapp/staas.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}
{% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <form action="" method="post">
        <h3>Fill out the form!</h3>
        <div class="form-group">
          {{ form.as_p }}
          {% csrf_token %}
        </div>
          <center><input type="submit" class="btn btn-primary" value="submit"/></center>
        </form>
      </div>
{% endblock %}

django_folder/hadoop_start/templates/myapp/validation.html
{% extends "myapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h3>Validation Successful</h3>
  <h3>Welcome to Storage as a service!</h3>
</div>

{% endblock %}